# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}: {
  imports = [
    # Generated by nixos-anywhere during install (--generate-hardware-config
    # nixos-generate-config ./hardware-configuration.nix) - does not exist
    # until then. That generator always writes fileSystems/swapDevices
    # entries, which conflict with disko.nix's (disko is already the source
    # of truth for those paths) and make the install's own build step fail.
    # Fix: let the first nixos-anywhere run write this file (its build
    # failing is fine, the file lands regardless), delete the generated
    # fileSystems.*/swapDevices entries here, then re-run nixos-anywhere
    # WITHOUT --generate-hardware-config to actually install.
    ./hardware-configuration.nix
    ./disko.nix
    ./modules/nixos
    ./modules/wm/niri
    ../../modules/nixos
  ];

  stylix = {
    enable = true;
    base16Scheme = "${pkgs.base16-schemes}/share/themes/gruvbox-dark-hard.yaml";
  };

  nix.nixPath = ["nixpkgs=${inputs.nixpkgs}"];

  users.users.cathe = {
    isNormalUser = true;
    description = "cathe";
    extraGroups = [
      "networkmanager"
      "wheel"
      "samba"
    ];
  };

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    backupFileExtension = "backup";
  };

  boot.kernel.sysctl."fs.inotify.max_user_watches" = 1048576;

  # Bootloader
  boot.loader.systemd-boot = {
    enable = true;
    configurationLimit = 15;
  };
  boot.loader.efi.canTouchEfiVariables = true;

  # Laptop power management
  services.power-profiles-daemon.enable = true;

  # Garbage Collection
  nix.gc = {
    automatic = true;
    dates = "*-*-* 21:00:00";
    options = "--delete-older-than 7d";
  };
  nix.settings = {
    keep-outputs = true;
  };

  networking.hostName = "nixos-laptop"; # Define your hostname.

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Europe/London";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_GB.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_GB.UTF-8";
    LC_IDENTIFICATION = "en_GB.UTF-8";
    LC_MEASUREMENT = "en_GB.UTF-8";
    LC_MONETARY = "en_GB.UTF-8";
    LC_NAME = "en_GB.UTF-8";
    LC_NUMERIC = "en_GB.UTF-8";
    LC_PAPER = "en_GB.UTF-8";
    LC_TELEPHONE = "en_GB.UTF-8";
    LC_TIME = "en_GB.UTF-8";
  };

  # Internal Drives
  services.udisks2.enable = true;

  # Enable OpenGL
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # Enable the X11 windowing system.
  services.xserver = {
    enable = true;
    # Configure keymap in X11
    xkb = {
      layout = "gb";
      variant = "";
    };
  };

  # Configure console keymap
  console.keyMap = "uk";

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # nix
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];
  programs.nix-index = {
    enable = true;
    enableZshIntegration = true;
  };
  programs.command-not-found.enable = false;

  environment.systemPackages = with pkgs; [
    wget
    autoconf
    git
    zsh
    zsh-nix-shell
    tmux
    xplr

    fzf
    gh

    nix
    nixd
    nixfmt
    alejandra
    nix-search-cli
    nix-index

    neovide
    flatpak
    libappimage

    ffmpeg
    vlc
    samba
    avahi

    wireplumber
    noto-fonts

    ## for thumnails
    ffmpeg-headless
    ffmpegthumbnailer
    gdk-pixbuf
  ];

  # https://wiki.nixos.org/wiki/Thumbnails
  environment.pathsToLink = [
    "share/thumbnailers"
  ];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # Did you read the comment?

  # Automatic Updates
  system.autoUpgrade = {
    enable = false;
    allowReboot = false;
  };
}
