# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}: {
  imports = [
    # Generated by nixos-anywhere during install (--generate-hardware-config
    # nixos-generate-config ./hardware-configuration.nix). Confirmed via a
    # real install run: nixos-anywhere's own generation already omits
    # fileSystems/swapDevices (disko.nix is the source of truth for those),
    # so no manual editing of the generated file is needed - it builds
    # cleanly as-is. disko re-runs on every nixos-anywhere invocation
    # though, so pass --disk-encryption-keys (see disko.nix) every time.
    ./hardware-configuration.nix
    ./disko.nix
    ./modules/nixos
    ./modules/wm/gnome
    ./modules/wm/niri
    ../../modules/nixos
  ];

  stylix = {
    enable = true;
    base16Scheme = "${pkgs.base16-schemes}/share/themes/gruvbox-dark-hard.yaml";
  };

  nix.nixPath = ["nixpkgs=${inputs.nixpkgs}"];

  users.users.cathe = {
    isNormalUser = true;
    description = "cathe";
    extraGroups = [
      "networkmanager"
      "wheel"
      "samba"
    ];
  };

  # max manages his own home-manager config independently, from his own
  # GitHub repo (bootstrapped from the templates#home-manager-user template)
  # - deliberately NOT wired into home-manager.users here, see README.md.
  users.users.max = {
    isNormalUser = true;
    description = "max";
    extraGroups = [
      "networkmanager"
      "wheel"
    ];
  };

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    backupFileExtension = "backup";
  };

  boot.kernel.sysctl."fs.inotify.max_user_watches" = 1048576;

  # Bootloader
  boot.loader.systemd-boot = {
    enable = true;
    configurationLimit = 15;
  };
  boot.loader.efi.canTouchEfiVariables = true;

  # Laptop power management
  services.power-profiles-daemon.enable = true;

  # Garbage Collection
  nix.gc = {
    automatic = true;
    dates = "*-*-* 21:00:00";
    options = "--delete-older-than 7d";
  };
  nix.settings = {
    keep-outputs = true;
  };

  networking.hostName = "nixos-laptop"; # Define your hostname.

  # Enable networking
  networking.networkmanager.enable = true;

  # eduroam (cathe only - max sets up his own independently via nmcli/GNOME
  # Settings, see README.md). The CA cert is public (downloaded from
  # https://student.kent.ac.uk/studies/wi-fi/manual, confirmed to be Kent's
  # own self-signed University of Kent Root CA - use the Root CA cert, not
  # the issuing CA or the wifi server cert itself), so it's committed here;
  # the identity/password are NOT - they're substituted at activation time
  # from an out-of-band file. See README.md "manual setup (non-nix)" for the
  # one-time setup of that file. Kent's docs give the identity format as
  # <kent-username>@kent.ac.uk and don't mention an anonymous outer identity,
  # so none is configured here.
  environment.etc."eduroam-ca.cer" = {
    source = ./eduroam-ca.cer;
    mode = "0444";
  };

  # ensureProfiles.environmentFiles is strictly typed as an absolute path -
  # it does NOT support systemd's "-" (optional file) prefix. Instead,
  # pre-create the secrets directory/file declaratively (0600, root-owned,
  # left alone if it already exists) so the path always exists by the time
  # NetworkManager-ensure-profiles.service runs, even before it's filled in.
  # "C" rules below seed each account's AccountsService session preference
  # (/var/lib/AccountsService/users/<name>, the same file GDM's own session
  # switcher writes to via Session=/SessionType= - confirmed against
  # accountsservice's own source, src/user.c) so cathe defaults to niri and
  # max defaults to gnome. "C" only copies the source into place if the
  # target is missing, so this is just an *initial* default: once
  # AccountsService itself updates the file (e.g. someone picks a different
  # session from the GDM switcher), that sticks and is never overwritten
  # back by this rule. Deliberately NOT using
  # services.displayManager.defaultSession for this - that forces ALL normal
  # user accounts to the given session on every single GDM start (gdm.nix's
  # own preStart comment literally says "ignore session history"), which
  # would reset cathe's niri choice back on every reboot too.
  systemd.tmpfiles.rules = let
    accountsServiceSession = name: session:
      pkgs.writeText "accountsservice-${name}-session" ''
        [User]
        Session=${session}
        SessionType=wayland
      '';
  in [
    "d /etc/nixos/secrets 0700 root root -"
    "f /etc/nixos/secrets/eduroam-cathe.env 0600 root root -"
    "C /var/lib/AccountsService/users/cathe 0600 root root - ${accountsServiceSession "cathe" "niri"}"
    "C /var/lib/AccountsService/users/max 0600 root root - ${accountsServiceSession "max" "gnome"}"
  ];

  networking.networkmanager.ensureProfiles = {
    environmentFiles = ["/etc/nixos/secrets/eduroam-cathe.env"];
    profiles.eduroam-cathe = {
      connection = {
        id = "eduroam-cathe";
        type = "wifi";
        permissions = "user:cathe";
      };
      wifi = {
        ssid = "eduroam";
        mode = "infrastructure";
      };
      wifi-security = {
        key-mgmt = "wpa-eap";
      };
      "802-1x" = {
        eap = "peap";
        phase2-auth = "mschapv2";
        identity = "$EDUROAM_IDENTITY";
        ca-cert = "/etc/eduroam-ca.cer";
        # Kent's own guide says the server cert should present
        # CN=wifi.kent.ac.uk ("if it says something else please contact
        # us") - pin to that as an extra check beyond just the CA chain.
        domain-suffix-match = "wifi.kent.ac.uk";
        password = "$EDUROAM_PASSWORD";
      };
    };
  };

  # Set your time zone.
  time.timeZone = "Europe/London";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_GB.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_GB.UTF-8";
    LC_IDENTIFICATION = "en_GB.UTF-8";
    LC_MEASUREMENT = "en_GB.UTF-8";
    LC_MONETARY = "en_GB.UTF-8";
    LC_NAME = "en_GB.UTF-8";
    LC_NUMERIC = "en_GB.UTF-8";
    LC_PAPER = "en_GB.UTF-8";
    LC_TELEPHONE = "en_GB.UTF-8";
    LC_TIME = "en_GB.UTF-8";
  };

  # Internal Drives
  services.udisks2.enable = true;

  # Enable OpenGL
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # Enable the X11 windowing system.
  services.xserver = {
    enable = true;
    # Configure keymap in X11
    xkb = {
      layout = "gb";
      variant = "";
      # compose:ralt makes right-Alt a Compose key, e.g. Compose ' e -> é
      options = "compose:ralt";
    };
  };

  # Configure console keymap
  console.keyMap = "uk";

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # nix
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];
  programs.nix-index = {
    enable = true;
    enableZshIntegration = true;
  };
  programs.command-not-found.enable = false;

  environment.systemPackages = with pkgs; [
    wget
    ntfs3g
    autoconf
    git
    zsh
    zsh-nix-shell
    tmux
    xplr

    fzf
    gh

    nix
    nixd
    nixfmt
    alejandra
    nix-search-cli
    nix-index

    neovide
    flatpak
    libappimage

    ffmpeg
    vlc
    samba
    avahi

    wireplumber
    noto-fonts

    ## for thumnails
    ffmpeg-headless
    ffmpegthumbnailer
    gdk-pixbuf
  ];

  # https://wiki.nixos.org/wiki/Thumbnails
  environment.pathsToLink = [
    "share/thumbnailers"
  ];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # Did you read the comment?

  # Automatic Updates
  system.autoUpgrade = {
    enable = false;
    allowReboot = false;
  };
}
