# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/80acd108-6382-4fef-b428-d834a8027c94";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/058E-CFC6";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/759794c7-2c5b-4b95-b400-41243154961e"; }
  ];

  #  fileSystems."mnt/data" =
  #    { device = "/dev/disk/by-uuid/6EDA6CCADA6C905F";
  #      fsType = "ntfs-3g";
  #       options = [ "rw" "uid=1000" "nofail"  "x-systemd.mount-timeout=180" ];
  #    };

  #  fileSystems."mnt/archive" =
  #    { device = "/dev/disk/by-uuid/6EDA6CCADA6C905F";
  #      fsType = "ntfs-3g";
  #       options = [ "rw" "uid=1000" "nofail" "x-systemd.mount-timeout=180" ];
  #    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
